name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Go
      uses: actions/setup-go@4de67c04ab4550d5b619aef0b37cd4ec732d7b37 # v.5.4.0
      with:
        go-version-file: 'go.mod'

    - name: Run tests
      run: go test ./... -v -race
